= Loud Voice Services - Code Assignment

== Description

VirtualBank (a ficticious Fintech) asked you to build their MVP which consists of creating a new account, deposit and withdraw money.

== Bank as a Service

=== Requirements

Develop a REST api that:

1. Allows a client to register a new account that accepts an email and password and provide any type of authentication (JWT, Auth Token, etc)
  
==== For example: 
[source]
----
curl -d "email=john@test.com&password=test123" -X POST http://localhost:3000/accounts
----

2. Expose a method that allows the customer to deposit money into their account
3. Expose a method that allows the customer to withdraw money from their account
4. Expose method to check account balance
    
== Stretch goals
1. Document your API following link:OpenAPI[https://swagger.io/specification/] standards.
2. Build a UI that consumes your API
  - Bonus: build the front-end using Vue.JS
3. Deploy your API somewhere and include the url in your README so we can try it out without having to run it
4. Dockerize you app

== Notes
1. Describe your train of thought as much as you can and any assumption that you might have during the develop of your solution
2. Feel free to be creative with your solution. There is no 100% correct solution. We are just as interested in how you approach the problem as we are in the actual solution.
3. This service should be written in Python or Java;
4. No UI is necessary if your service can be called using cURL;
5. You can use any mechanism for keeping saving the data;
6. Feel free to write some tests;

== Submission
1. Fork this repository
2. Develop your code
3. Create a Pull Request with your solution
