# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class History(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, email: str=None, _from: datetime=None, to: datetime=None):  # noqa: E501
        """History - a model defined in Swagger

        :param email: The email of this History.  # noqa: E501
        :type email: str
        :param _from: The _from of this History.  # noqa: E501
        :type _from: date
        :param to: The to of this History.  # noqa: E501
        :type to: date
        """
        self.swagger_types = {
            'email': str,
            '_from': datetime,
            'to': datetime
        }

        self.attribute_map = {
            'email': 'email',
            '_from': 'from',
            'to': 'to'
        }

        self._email = email
        self.__from = _from
        self._to = to

    @classmethod
    def from_dict(cls, dikt) -> 'History':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The History of this History.  # noqa: E501
        :rtype: History
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this History.


        :return: The email of this History.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this History.


        :param email: The email of this History.
        :type email: str
        """

        self._email = email

    @property
    def _from(self) -> datetime:
        """Gets the _from of this History.


        :return: The _from of this History.
        :rtype: date
        """
        return self.__from

    @_from.setter
    def _from(self, _from: datetime):
        """Sets the _from of this History.


        :param _from: The _from of this History.
        :type _from: date
        """

        self.__from = _from

    @property
    def to(self) -> datetime:
        """Gets the to of this History.


        :return: The to of this History.
        :rtype: date
        """
        return self._to

    @to.setter
    def to(self, to: datetime):
        """Sets the to of this History.


        :param to: The to of this History.
        :type to: date
        """

        self._to = to
