# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Order(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, email: str=None, value: float=None):  # noqa: E501
        """Order - a model defined in Swagger

        :param email: The email of this Order.  # noqa: E501
        :type email: str
        :param value: The value of this Order.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'email': str,
            'value': float
        }

        self.attribute_map = {
            'email': 'email',
            'value': 'value'
        }

        self._email = email
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'Order':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Order of this Order.  # noqa: E501
        :rtype: Order
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this Order.


        :return: The email of this Order.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Order.


        :param email: The email of this Order.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def value(self) -> float:
        """Gets the value of this Order.


        :return: The value of this Order.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this Order.


        :param value: The value of this Order.
        :type value: float
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
